"use client";

import { useEffect, useState } from "react";
import { FileText, Plus, X, Download, Eye } from "lucide-react";
import { formatDate, getStatusColor, cn } from "@/lib/utils";

interface TargetOption { id: string; name: string; }

interface ReportData {
  id: string;
  title: string;
  findings: string;
  impactAnalysis: string;
  reproduction: string;
  mitigation: string;
  status: string;
  createdAt: string;
  target: { name: string };
}

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportData[]>([]);
  const [targets, setTargets] = useState<TargetOption[]>([]);
  const [showModal, setShowModal] = useState(false);
  const [previewReport, setPreviewReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [form, setForm] = useState({
    targetId: "",
    title: "",
    findings: "",
    impactAnalysis: "",
    reproduction: "",
    mitigation: "",
    status: "DRAFT",
  });

  const fetchData = async () => {
    try {
      const [rRes, tRes] = await Promise.all([
        fetch("/api/reports"),
        fetch("/api/targets"),
      ]);
      const rData = await rRes.json();
      const tData = await tRes.json();
      setReports(Array.isArray(rData) ? rData : []);
      setTargets(Array.isArray(tData) ? tData : []);
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchData(); }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      setShowModal(false);
      setForm({ targetId: "", title: "", findings: "", impactAnalysis: "", reproduction: "", mitigation: "", status: "DRAFT" });
      fetchData();
    } catch (e) { console.error(e); }
  };

  const exportMarkdown = (report: ReportData) => {
    const md = `# Security Report: ${report.title}

**Target:** ${report.target.name}
**Status:** ${report.status}
**Date:** ${formatDate(report.createdAt)}

---

## Findings

${report.findings}

## Impact Analysis

${report.impactAnalysis}

## Reproduction Steps

${report.reproduction}

## Mitigation Recommendations

${report.mitigation}

---

*Generated by Cikopiboysec — AI Security Research Workspace*
`;
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.replace(/\s+/g, "_")}_report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-3">
            <div className="flex items-center justify-center w-9 h-9 rounded-lg" style={{ backgroundColor: "rgba(59, 130, 246, 0.1)", color: "var(--color-accent-blue)" }}>
              <FileText size={20} />
            </div>
            <span className="text-gradient">Security Reports</span>
          </h1>
          <p className="text-sm mt-1" style={{ color: "var(--color-text-secondary)" }}>
            Generate and export security research reports
          </p>
        </div>
        <button onClick={() => setShowModal(true)} className="btn-primary">
          <Plus size={16} /> New Report
        </button>
      </div>

      <div className="glow-line" />

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="animate-spin rounded-full h-8 w-8 border-2 border-transparent" style={{ borderTopColor: "var(--color-accent-cyan)" }} />
        </div>
      ) : reports.length === 0 ? (
        <div className="empty-state">
          <FileText size={48} />
          <h3 className="text-lg font-semibold mt-4" style={{ color: "var(--color-text-primary)" }}>No reports yet</h3>
          <p className="text-sm" style={{ color: "var(--color-text-muted)" }}>Create your first security report</p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map((report) => (
            <div key={report.id} className="glass-card p-5">
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className={cn("badge text-[10px]", getStatusColor(report.status))}>{report.status}</span>
                    <span className="badge bg-zinc-500/20 text-zinc-400 border-zinc-500/30 text-[10px]">{report.target.name}</span>
                  </div>
                  <h3 className="font-semibold text-sm" style={{ color: "var(--color-text-primary)" }}>{report.title}</h3>
                  <p className="text-xs mt-1 line-clamp-2" style={{ color: "var(--color-text-secondary)" }}>{report.findings}</p>
                </div>
                <div className="flex items-center gap-2 ml-4 flex-shrink-0">
                  <button onClick={() => setPreviewReport(report)} className="btn-secondary text-xs px-2 py-1">
                    <Eye size={12} />
                  </button>
                  <button onClick={() => exportMarkdown(report)} className="btn-primary text-xs px-2 py-1">
                    <Download size={12} /> .md
                  </button>
                </div>
              </div>
              <p className="text-[10px] mt-2" style={{ color: "var(--color-text-muted)" }}>{formatDate(report.createdAt)}</p>
            </div>
          ))}
        </div>
      )}

      {/* Preview Modal */}
      {previewReport && (
        <div className="modal-overlay" onClick={() => setPreviewReport(null)}>
          <div className="modal-content max-w-3xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-lg font-bold" style={{ color: "var(--color-text-primary)" }}>Report Preview</h2>
              <div className="flex gap-2">
                <button onClick={() => exportMarkdown(previewReport)} className="btn-primary text-xs">
                  <Download size={12} /> Export
                </button>
                <button onClick={() => setPreviewReport(null)} className="p-1 rounded-lg hover:bg-white/5" style={{ color: "var(--color-text-muted)" }}><X size={18} /></button>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-bold" style={{ color: "var(--color-text-primary)" }}>{previewReport.title}</h3>
                <p className="text-xs mt-1" style={{ color: "var(--color-text-muted)" }}>Target: {previewReport.target.name} | {formatDate(previewReport.createdAt)}</p>
              </div>
              <div className="glow-line" />
              {[
                { label: "Findings", content: previewReport.findings },
                { label: "Impact Analysis", content: previewReport.impactAnalysis },
                { label: "Reproduction Steps", content: previewReport.reproduction },
                { label: "Mitigation", content: previewReport.mitigation },
              ].map((section) => (
                <div key={section.label}>
                  <h4 className="text-sm font-semibold mb-2" style={{ color: "var(--color-accent-cyan)" }}>{section.label}</h4>
                  <p className="text-sm whitespace-pre-wrap" style={{ color: "var(--color-text-secondary)" }}>{section.content}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Create Modal */}
      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-content max-w-3xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-lg font-bold" style={{ color: "var(--color-text-primary)" }}>New Report</h2>
              <button onClick={() => setShowModal(false)} className="p-1 rounded-lg hover:bg-white/5" style={{ color: "var(--color-text-muted)" }}><X size={18} /></button>
            </div>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium mb-1.5" style={{ color: "var(--color-text-secondary)" }}>Target *</label>
                  <select required className="select-field" value={form.targetId} onChange={(e) => setForm({ ...form, targetId: e.target.value })}>
                    <option value="">Select target...</option>
                    {targets.map((t) => (<option key={t.id} value={t.id}>{t.name}</option>))}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium mb-1.5" style={{ color: "var(--color-text-secondary)" }}>Status</label>
                  <select className="select-field" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>
                    {["DRAFT", "REVIEW", "SUBMITTED", "ACCEPTED"].map((s) => (<option key={s}>{s}</option>))}
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-xs font-medium mb-1.5" style={{ color: "var(--color-text-secondary)" }}>Report Title *</label>
                <input required className="input-field" placeholder="e.g. Context Injection in Agent Tool Calls" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
              </div>
              <div>
                <label className="block text-xs font-medium mb-1.5" style={{ color: "var(--color-text-secondary)" }}>Findings *</label>
                <textarea required className="textarea-field" rows={4} placeholder="Describe the findings..." value={form.findings} onChange={(e) => setForm({ ...form, findings: e.target.value })} />
              </div>
              <div>
                <label className="block text-xs font-medium mb-1.5" style={{ color: "var(--color-text-secondary)" }}>Impact Analysis *</label>
                <textarea required className="textarea-field" rows={3} placeholder="What is the security impact?" value={form.impactAnalysis} onChange={(e) => setForm({ ...form, impactAnalysis: e.target.value })} />
              </div>
              <div>
                <label className="block text-xs font-medium mb-1.5" style={{ color: "var(--color-text-secondary)" }}>Reproduction Steps *</label>
                <textarea required className="textarea-field" rows={4} placeholder="Step-by-step reproduction..." value={form.reproduction} onChange={(e) => setForm({ ...form, reproduction: e.target.value })} />
              </div>
              <div>
                <label className="block text-xs font-medium mb-1.5" style={{ color: "var(--color-text-secondary)" }}>Mitigation *</label>
                <textarea required className="textarea-field" rows={3} placeholder="Suggested mitigations..." value={form.mitigation} onChange={(e) => setForm({ ...form, mitigation: e.target.value })} />
              </div>
              <div className="flex gap-3 pt-2">
                <button type="submit" className="btn-primary flex-1">Create Report</button>
                <button type="button" onClick={() => setShowModal(false)} className="btn-secondary">Cancel</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
